### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gkumbhat** [mgwidmann/httpoison_retry#4]
This is a great library. Thanks for creating a cool retry logic around HTTPoison.
Will it be possible to add a license to this repo?

**Comment by mgwidmann** [comment]
Send me a PR and I'll merge it. I don't have any particular preference.

**Comment by gkumbhat** [comment]
Thanks @mgwidmann . I have created following PR in this regard: https://github.com/mgwidmann/httpoison_retry/pull/5
